const CANVAS_WIDTH = 500;
const CANVAS_HEIGHT = 743;

const BACKGROUND_WIDTH = CANVAS_WIDTH;
const BACKGROUND_HEIGHT = 650;
const BACKGROUND_POSX = 0;
const BACKGROUND_POSY = 0;

const GROUND_WIDTH = CANVAS_WIDTH;
const GROUND_HEIGHT = CANVAS_HEIGHT - BACKGROUND_HEIGHT;

const PIPE_WIDTH = 80;
const PIPE_GAP = 180;
const PIPE_POSY = -5;

const BIRD_WIDTH = 50;
const BIRD_HEIGHT = 50;
const BIRD_POSX = 40;
const BIRD_POSY = CANVAS_HEIGHT / 2;

const GRAVITY = 0.2;
const ANTIGRAVITY = -5;

const PLAY_BUTTON_POSX = 130;
const PLAY_BUTTON_POSY = 400;
const PLAY_BUTTON_WIDTH = 200;
const PLAY_BUTTON_HEIGHT = 100;

const REPLAY_BUTTON_POSX = 130;
const REPLAY_BUTTON_POSY = 470;
const REPLAY_BUTTON_WIDTH = 200;
const REPLAY_BUTTON_HEIGHT = 100;
